name: citizens_voice_app
description: "A new Flutter project."
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
          sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  hive_flutter: ^1.1.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_crashlytics: ^4.1.3
  change_app_package_name: ^1.4.0
  firebase_analytics: ^11.3.3
  connectivity_plus: ^6.0.5
  bloc: ^8.1.4
  crypto: ^3.0.5
  animations: ^2.0.11
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.10+1
  device_preview: ^1.2.0
  slide_countdown: ^2.0.0
  carousel_slider: ^5.0.0
  syncfusion_flutter_charts: ^27.1.57
  http: ^1.2.2
  html: ^0.15.5
  chat_gpt_sdk: ^3.1.0
  flutter_widget_from_html: ^0.15.2
  skeletonizer: ^1.4.2
  flutter_spinkit: ^5.2.1
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/icons/fields/

  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Regular.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Bold.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Medium.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-SemiBold.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Light.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-ExtraLight.ttf
        - asset: assets/fonts/IBM_Plex_Sans_Arabic/IBMPlexSansArabic-Thin.ttf
    - family: Custom Icons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
flutter_intl:
  enabled: true


flutter_native_splash:
  color: "#D90429"
  icon_background_color: "#D90429"
  image: "assets/images/logo_transparent3.png"
  android_12:
    color: "#D90429"
    icon_background_color: "#D90429"
    image: "assets/images/logo_transparent3.png"

  android: true
  ios: true
  web: false

  fullscreen: true